### ISSUE TITLE
mui.newCard() Example doesn't work.

### ISSUE THREAD

**Issue by taigak** [arcadefx/material-ui#142]
2016/10/29

I wrote following example code in document(http://www.anedix.com/docs/mui/API/Cards/newCard.html).

```
    --
    -- Set up the card
    --
    local topHeight = mui.getScaleVal(100)
    local bottomHeight = mui.getScaleVal(150)
    mui.newCard({
        name = "demo-card",
        x = centerX * 0.7,
        y = centerY,
        topHeight = topHeight,
        bottomHeight = bottomHeight,
        width = display.contentWidth * 0.5,
        height = topHeight + bottomHeight,
        fillColor = {1, 1, 1, 1},
        fillColorBottom = {0.22, 0.55, 0.23},
        --strokeWidth = mui.getScaleVal(2),
        --strokeColor = {0.2, 0.2, 0.2},
        useShadow = true,
        --radius = mui.getScaleVal(5),
    })
```

I got this error.

![2016-10-29 23 18 47](https://cloud.githubusercontent.com/assets/10809323/19830223/2d8a4648-9e2e-11e6-9282-aaf25eaa4801.png)

but this error disappeared after I insert 'fillColorTop' in options.  
document says 'fillColorTop' and 'fillColorBottom' is optional.

document is wrong?

**Comment by arcadefx** [comment]
This has been addressed.  Thanks for reporting the issue.
