### ISSUE TITLE
Option useActualDimensions is always true

### ISSUE THREAD

**Issue by StevenWarren** [arcadefx/material-ui#143]
The init() function ignores setting useActualDimensions to false. Investigating I found this line in the init function that initializes useActualDimensions. This will always return true. If we pass true in our options table then that value will be used, but if we pass false then the default true is used. 

```lua
options.useActualDimensions = options.useActualDimensions or true
```

not sure if this is the most elegant way of handling it, but I just changed the line to 

```lua
  if options.useActualDimensions == false then
    options.useActualDimensions  = options.useActualDimensions
  else
    options.useActualDimensions = true
  end
```

**Comment by arcadefx** [comment]
This has been addressed. Thank you for reporting it.
