### ISSUE TITLE
Random issues as I've explored material-ui

### ISSUE THREAD

**Issue by bodily11** [arcadefx/material-ui#165]
1. If an icon button is less than mui.getScaleVal(150) it does not show up in the Corona Simulator. I can still click on where it should be to get the button animation, but the button does not show up. This makes positioning small icon buttons difficult.

2. Can I change the default font size of user inputted text in a text box? The text is very small by default and hard to see, so I would like to make it bigger.

3. Can I set the value property of a TextBox, maybe with a setTextBox.value method? I want the user to be able to submit multiple responses from the same text box. Right now I have to remove and reinstantiate the widget with no text to remove their previous response. I tried to set the value using setTextBox.value but it was not working.

4. The text field in a text box is the text that shows up initially but should be hidden when a user clicks on the text box. However, it doesn't go away when the user clicks on the text box so the user has to delete the existing text before inputting their response.

**Comment by arcadefx** [comment]
@bodily11 I can address the issues.

1. Investigating and could you send me the sample and screen size settings too? @bodily11
2. Fixed and not yet merged with master.
3. Fixed and not yet merged with master. Example: mui.setTextBoxValue("widget_name", "Some text goes here") and there is now mui.setTextFieldValue("widget_name", "your value") too.
4. Investigating

**Comment by bodily11** [comment]
I'm using 720x1280 (Samsung Galaxy S3 setting). In larger resolution settings the smaller button shows up. mui.getScaleVal(180) is the smallest visible button on the Samsung Galaxy S3 setting.

Button code:
mui.newIconButton({
        name = "help",
        text = "help",
        width = mui.getScaleVal(180),
        height = mui.getScaleVal(180),
        x = mui.getScaleVal(550),
        y = mui.getScaleVal(75),
        font = "MaterialIcons-Regular.ttf",
        textColor = { 1,1, 1, 1 },
        callBack = mui.actionSwitchScene,
})

**Comment by arcadefx** [comment]
Strange, I switch to the 720x1280 and did:

mui.newIconButton({
name = "help",
text = "help",
width = mui.getScaleVal(46),
height = mui.getScaleVal(46),
x = mui.getScaleVal(550),
y = mui.getScaleVal(75),
font = "MaterialIcons-Regular.ttf",
textColor = { 0,0, 0, 1 },  -- black button instead of white since i have white background
callBack = nil,
})
...and it showed up fine.

**Comment by bodily11** [comment]
Yeah, that is weird. I just checked a couple different resolutions and there is a different minimum size for each resolution where the button will no longer show up.

Screen capture of the issue happening https://goo.gl/photos/yipJxNq6egoC3c8d6.

Maybe I have an issue with my system environment.

**Comment by arcadefx** [comment]
I switched to portrait and used a dark background example:
Screen capture is here: [screenshot](http://www.anedix.com/fileshare/screenshot-help-button-issue-1.png)

Also..

1. Investigating
2. **Fixed and merged with master**.
3. **Fixed and merged with master**. Example: mui.setTextBoxValue("widget_name", "Some text goes here") and there is now mui.setTextFieldValue("widget_name", "your value") too.
4. Investigating

**Comment by arcadefx** [comment]
What does your mui.init() look like?

**Comment by bodily11** [comment]
I'm not giving it any specific parameters. I'm just using mui.init().

**Comment by arcadefx** [comment]
Ah, you are using Windows I think from the screen shot. I am on a MacBook Pro so let me switch over to my Windows 10 laptop and see what it does.

**Comment by arcadefx** [comment]
I downloaded latest Corona SDK daily build and used it on a Windows 10 Pro laptop.  It appears the same as the Macbook Pro screenshot.

**Comment by bodily11** [comment]
Well, I'm out of ideas. I don't know what would make a difference between our two systems. Would zoom or screen resolution affect it? It seems to be an isolated issue (to my system).

**Comment by arcadefx** [comment]
Depending on how you feel about it, could you Zip it up a portion of the code and send it to me? You can use dropbox or link and submit that link here:

[Submit Link](http://www.anedix.com/contact)

Then we can e-mail one another if needed too.

**Comment by bodily11** [comment]
There was a problem with your form. It said I had an error in one of my fields. I inputted all of them, so I don't know what the problem was. I'll just post the link here and I can remove it later once you have the code.

(edit: I downloaded and then removed the link)

**Comment by arcadefx** [comment]
@bodily11  I see the issue now.  In 'config.lua' comment out the resolution in there. 
```
		--[[--
		width = 320,
		height = 480, 
		--]]--
```

I think I see why and can make a work-a-round for it.  The library is using 640 and 960 for width depending on portrait etc.  Unless you pass in mui.init(nil,{minPixelScaleWidthForPortrait=[your width value]) or mui.init(nil,{minPixelScaleWidthForLandscape=[your width value]) and those match the config.  Let play with it.

**Comment by bodily11** [comment]
Did commenting out the resolution fix it on your machine? I commented it out but it didn't do anything.

**Comment by arcadefx** [comment]
I also changed the "help" button width and height to be 90.  Let me try this on the Windows 10.

**Comment by arcadefx** [comment]
Yep, worked fine there too.  I will keep looking at this one and try on another Windows computer.

**Comment by arcadefx** [comment]
4. The text field in a text box is the text that shows up initially but should be hidden when a user clicks on the text box. However, it doesn't go away when the user clicks on the text box so the user has to delete the existing text before inputting their response.

I think was addressed in another update, but let me know if it persists.  Going to close the issue for now.
