### ISSUE TITLE
newIconButton is disapear

### ISSUE THREAD

**Issue by lmy46** [arcadefx/material-ui#201]
2017/03/06

newIconButton text is disapear

But it will apear...But text width will error...
`local font = native.systemFont
    -- if options.font ~= nil then
    --     font = options.font
    -- end`

and u must comment follow code:
`local tw = textToMeasure.contentWidth
    -- local th = textToMeasure.contentHeight

    -- if options.isFontIcon == true then
    --     tw = fontSize
    --     if M.isMaterialFont(options.font) == true then
    --         options.text = M.getMaterialFontCodePointByName(options.text)
    --     end
    -- elseif string.len(options.text) < 2 then
    --     tw = fontSize
    -- end`

It will run correct. But can Use ur Font...
What's happen?

My Corona SDK is 2017 3048

－－－－－－－－－－－－－
2017/03/08

I know what's happen...
Ur font MaterialIcons-Regular.ttf can appear 'Lower case letters' & 'digit'
Must Use MaterialIcons-Regular.otf

**Comment by arcadefx** [comment]
Hi,

Yah I ran into 'font' issues when trying to use 'ttf' and seems 'otf' is best supported.  I will see about addressing it all fairly soon.
