### ISSUE TITLE
mui.newTextField - Content resize on edit

### ISSUE THREAD

**Issue by jrogerbentley** [arcadefx/material-ui#213]
I created a quick project to look at your tool. When I edit the text field the edit text resizes to a smaller text. Is there anyway to prevent that behavior. Test phone Samsung GT-NT7100, Android 4.1.1

**Comment by arcadefx** [comment]
Ah, in the process of releasing it, I missed the coding to set the text box font.  Let me fix it and test it on a Samsung Galaxy S4 (4.1.1).  I will have an update in 1 day for it.

**Comment by arcadefx** [comment]
@jrogerbentley 
I fixed it.  However, I noticed on my Samsung Galaxy S4 the text box shows up fine and then suddenly there is a zoomed in version by the OS.  Does it show you one text box or two?

**Comment by jrogerbentley** [comment]
Thanks for the work! I will download now.

I only had one instance of each text box.

BTW - I have made a few small tweaks in the copy I am playing with. Do you have any interest it them or other changes I might make? If so what is the right process for you to code review and accept these as new baseline features.

ALSO—
Do you do any contract work with Corona? We have a business application and more work then I can handle. If you are interested, please let me know and we can discuss how you might be able to move my project forward.

Roger

**Comment by jrogerbentley** [comment]
Ok I loaded the build.
I think I see what you are talking about. It is like a brief copy of the field. No I did not have this before todays build. Last prior update was yesterday. However, when I build to the device, I do not see the 2nd, temporary copy of the field value. So I think this may be a emulator issue only. 

Roger

**Comment by arcadefx** [comment]
Yah, I want the community to make tweaks and changes.  I can review the code submitted and work it in or if it's easy to 'merge' I will review the pull request.

I don't have any capacity at the moment for contract work. However, in the coming months that will change.
