### ISSUE TITLE
Showing a diff value on touch on a newSelect truncates value

### ISSUE THREAD

**Issue by willcastillo** [arcadefx/material-ui#239]
Hey...

By default, M.onRowTouchSelector shows the key/index of the touched item. I'd like to show the text instead.

I tried to do this:
`muiData.widgetDict[parentName]["selectorfieldfake"].text = muiTarget.params.text`

... but the UI shows only the first couple of characters.  Can't figure out why. Any idea?

**Comment by arcadefx** [comment]
@willcastillo Could you send me a screen shot?

**Comment by arcadefx** [comment]
@willcastillo  This is fixed.
