### ISSUE TITLE
mui.newRadioGroup not showing

### ISSUE THREAD

**Issue by ozaksu** [arcadefx/material-ui#245]
I create a mui.newRadioGroup. However the following occurs depending on the parent I set:

- if I set the parent to be scene group name "parent = settingsGroup" then the controls disappear completely.
- if I set the parent to be "parent = mui.getParent()" then the controls show up though changing scenes does not remove the controls. The controls are still visible between scenes.

All the other controls that I've placed work as expected. For example, the newToggleSwitch below works fine, though the newRadioGroup doesn't.

am I doing something wrong or what do I need to change?

        mui.newToggleSwitch({
        parent = mui.getParent(),
        name = "soundToggle",
        size = mui.getScaleVal(55),
        x = soundText.x + soundText.width + mui.getScaleVal(50),
        y = soundText.y + (soundText.height / 2),
        textColorOff = { 0.57, 0.85, 1, 1 },
        textColor = { 0.25, 0.75, 1, 1 },
        backgroundColor = { 0.74, 0.88, 0.99, 1 },
        backgroundColorOff = { 0.82, 0.95, 0.98, 1 },
        isChecked = toggleChecked,
        value = toggleValue, -- if switch is in the on position it's 100 else nil
        callBack = onSoundSwitchRelease
    })

    mui.newRadioGroup({
        parent = mui.getParent(),
        name = "noteTextRadio",
        width = 100,
        height = 50,
        x = noteTextHeading.x + mui.getScaleVal(50),
        y = noteTextHeading.y + noteTextHeading.height + mui.getScaleVal(20) + (noteTextHeading.height / 2),
        layout = "horizontal",
        labelFont = native.systemFont,
        textColor = { 0, 0, 0 },
        labelColor = { 0, 0, 0 },
        callBack = radioSwitchListener,

        list = {
            { key = "Do/Re/Mi..", value = "1", isChecked = false },
            { key = "C/D/E..", value = "2", isChecked = false }
        }
    })
`

**Comment by arcadefx** [comment]
@ozhikaye thanks for reporting it.  I will review and get a solution in place real soon.

**Comment by arcadefx** [comment]
@ozhikaye 

I tried it out and it's working.  Here is a demo using your radio button and switching to another scene.  The radio buttons show and get removed.  Let me know if you have any problems with it.

[radio-buttons.zip](https://github.com/arcadefx/material-ui/files/1145201/radio-buttons.zip)
