### ISSUE TITLE
Problem with Font Icon

### ISSUE THREAD

**Issue by bbmachado** [arcadefx/material-ui#256]
Hi,

I try this button, but don´t show the icon on the screen.

mui.newCircleButton({
        parent = mui.getParent(),
        name = "localizarclienteButton",
        text = "search",
		radius = mui.getScaleVal(60),
        x = centerX + centerX/2+30,
        y = mui.getScaleVal(100),
        isFontIcon = true,
        font = mui.materialFont,
        textColor = corbranco,
        fillColor = corfundobotao,
        textAlign = "center",
		useShadown = true,
        callBack = mui.actionSwitchScene,
        callBackData = {
            sceneDestination = "fotos",
            sceneTransitionColor = cortransicao,
            sceneTransitionAnimation = true
        } 
    })

Try to use the example in repository, but don´t show the icons too.

What can I do?

Thanks,
Breno

**Comment by arcadefx** [comment]
@bbmachado are you using 0.1.99? Be sure to pull the latest.  What environment are you using to develop in? (Windows or Mac)

I will try your example and see what it does.

**Comment by arcadefx** [comment]
@bbmachado 

Here is an example I used and it worked based on your code above..

```
    local centerX = display.contentWidth / 2
    local corbranco = {0.13, 0.12, 0.12,1}
    local corfundobotao = {1, 1, 1 }

    mui.newCircleButton({
        parent = mui.getParent(),
        name = "localizarclienteButton",
        text = "search",
        radius = mui.getScaleVal(60),
        x = centerX + centerX/2,
        y = mui.getScaleVal(100),
        isFontIcon = true,
        font = mui.materialFont,
        textColor = corbranco,
        fillColor = corfundobotao,
        textAlign = "center",
        useShadown = true,
        callBack = mui.actionSwitchScene,
        callBackData = {
            sceneDestination = nil,
            sceneTransitionColor = cortransicao,
            sceneTransitionAnimation = true
        }
    })

```

**Comment by bbmachado** [comment]
My enviroment is: 

Windows 7 Professional
Corona SDK version 2017.3068 (2017.3.31)
Material Design - Last version in repository

Try using your code and doesn´t work. Show the button, but not the icon.

The variable mui.materialFont ir right, and the font file exist in the right place.

Any idea?

Thank

![image](https://user-images.githubusercontent.com/26714028/30111065-a8d5a082-92e2-11e7-8933-b466725636c6.png)

**Comment by arcadefx** [comment]
@bbmachado, I will try it out on Windows 7 Prof. when I get back home this evening.   I am using 2017.3129 on Mac OS X and have a Windows 7 Pro laptop.

**Comment by arcadefx** [comment]
@bbmachado I tried it on Windows 7 Pro and no issues.  Do you have an icon-font/ folder in the project you are working on?

**Comment by bbmachado** [comment]
@arcadefx yes, the folder is ok too. Try to use your example and show too. See:

![image](https://user-images.githubusercontent.com/26714028/30230830-628f379a-94be-11e7-9b50-5ea446affb46.png)

Do you have any sugestion?

**Comment by arcadefx** [comment]
@bbmachado would it be possible to send me part of your project? I want to see why it isn't working. I loaded the version of CoronaSDK you have onto a Windows 10 Pro that never had CoronaSDK on it. It worked fine there. 

You can send me direct e-mails using: services at anedix.com

**Comment by arcadefx** [comment]
@bbmachado could you send me the console log output?  Does it error trying to find the font?
