### ISSUE TITLE
newCard

### ISSUE THREAD

**Issue by StevenWarren** [arcadefx/material-ui#266]
In the [documentation for Cards](http://www.anedix.com/docs/mui/API/Cards/newCard.html) there are some attributes that seem to not be implemented currently. 

```
topHeight/bottomHeight (required)

Number. The top and bottom height dimensions of the card.

fillColorTop (optional)

Table. The RGB(A for alpha/transparency) colors in percent to use for the top part of card.

fillColorBottom (optional)

Table. The RGB(A for alpha/transparency) colors in percent to use for the whole card.
```
I looked at the source and do not see them in the options.

**Comment by arcadefx** [comment]
@StevenWarren I will get those two back in there. I took them out for refactoring.

**Comment by arcadefx** [comment]
@StevenWarren I updated the card documentation and the card module.
