### ISSUE TITLE
Icons do not look good in some android versions

### ISSUE THREAD

**Issue by solcacorona** [arcadefx/material-ui#271]
Greetings. The graphic is self-explanatory (correct version with android 7). 

That could be happening?

Thanks in advance for the answer and this is a library with a lot of potential.

Solón

![icons_material_bad](https://user-images.githubusercontent.com/38535299/39002721-c6e89ff6-43be-11e8-8f67-c94744893cca.png)

**Comment by solcacorona** [comment]
Adding info, my log:
![image](https://user-images.githubusercontent.com/38535299/39008588-b8cecd0e-43ce-11e8-8f8a-17b623dee510.png)

**Comment by arcadefx** [comment]
@solcacorona I uploaded the .otf font to the `icon-font` folder. Be sure to copy it into your project.

**Comment by solcacorona** [comment]
Thank you.

That resolved my issue.

Regards,

SolCa

**Comment by arcadefx** [comment]
@solcacorona awesome! :)
